dist: xenial
sudo: false
language: ruby
rvm:
  - 2.4.5
  - 2.5.3
  - 2.6.0
  - ruby-head
branches:
  only:
    - master
cache: bundler
before_install:
  - travis_retry gem update --system
  - travis_retry gem install bundler
install:
  - travis_retry bundle
  - gem build ip-lookup.gemspec
  - gem install ./ip-lookup-*.gem
notifications:
  email: false
